### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by whitetigle** [MangelMaxime/Thot#8]
Hi!
And thanks for the great work @MangelMaxime!

I currently have a record typed like this:

```f#
type Test =
  {
    _id:string
    _rev:string option
    name:string
  }
```

The `_rev` field is optional because my server can either send me objects filled with `_id `or `_id` and `_rev`.

So I have tried this:

```f#
type Test =
  {
    _id:string
    _rev:string option
    name:string
  }
  static member Decoder =
      decode
          (fun id rev name ->
              { _id = id
                _rev = rev 
                name = name
              } : Test)
          |> required "_id" string
          |> optional "_rev" (string option)
          |> required "name" string
```

Butit's not the good way to do this. Would you have any idea? Thanks!

**Comment by MangelMaxime** [comment]
Here is the decoder fixed:

```fs
type Test =
  { _id:string
    _rev:string option
    name:string }

    static member Decoder =
      decode
          (fun id rev name ->
              { _id = id
                _rev = rev 
                name = name
              } : Test)
          |> required "_id" string
          |> optional "_rev" (option string) None
          |> required "name" string
```

The `optional` decoder take this arguments:
- `key`: string to access the property
- `valDecoder`: decoder used if the key is present
- `fallback`: value return if the key is not present

So here if the key is not present, we return `None` but you could also return `Some "not present"` because the type is valid.

Also, i would personally write it like that:

```fs
type Test =
  { Id:string
    Rev:string option
    Name:string }

    static member Decoder =
      decode
          (fun id rev name ->
              { Id = id
                Rev = rev 
                Name = name
              } : Test)
          |> required "_id" string
          |> optional "_rev" (option string) None
          |> required "name" string
```

Because the benefit of the decoder, is that you don't have to write your type to match the Json format. It's like a "brigde" between two worlds :) So you can a record write following the F# convention or your convention even if the json isn't.

**Comment by whitetigle** [comment]
> Because the benefit of the decoder, is that you don't have to write your type to match the Json format. It's like a "brigde" between two worlds :)

That's awesome! 👏 
Thanks @MangelMaxime
